// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ModelNameParser = require("./utils/modelNameParser").default;

function modelNameParser(prim0, prim1) {
  return new ModelNameParser(prim0, prim1);
}

function checkAndModifyModelName(generic, name) {
  var parser = new ModelNameParser(name, generic);
  Curry._1(parser.parse, undefined);
  var struct = Curry._1(parser.getData, undefined);
  var g = [
    "List",
    "Map"
  ];
  if (g.includes(struct.name)) {
    return /* Fail */0;
  } else {
    return /* Success */{
            _0: struct
          };
  }
}

exports.modelNameParser = modelNameParser;
exports.checkAndModifyModelName = checkAndModifyModelName;
/* ./utils/modelNameParser Not a pure module */
