// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Api = require("./api").default;
var Model = require("./model").default;
var Js_option = require("rescript/lib/js/js_option.js");
var ApiTool = require("./v3/apiTool").default;
var ModelTool = require("./v3/modelTool").default;

function api(prim0, prim1, prim2) {
  return new Api(prim0, prim1, prim2);
}

function apiV3(prim0, prim1, prim2) {
  return new ApiTool(prim0, prim1, prim2);
}

function model(prim0, prim1) {
  return new Model(prim0, prim1);
}

function modelV3(prim0, prim1) {
  return new ModelTool(prim0, prim1);
}

function getIsVersion3(data) {
  var v = Js_option.some(data.openapi);
  if (v !== undefined) {
    return v.startsWith("3");
  } else {
    return false;
  }
}

function makeApi(data) {
  var isVersion3 = getIsVersion3(data);
  if (isVersion3) {
    return apiV3;
  } else {
    return api;
  }
}

function makeModel(data) {
  var isVersion3 = getIsVersion3(data);
  if (isVersion3) {
    return modelV3;
  } else {
    return model;
  }
}

exports.api = api;
exports.apiV3 = apiV3;
exports.model = model;
exports.modelV3 = modelV3;
exports.getIsVersion3 = getIsVersion3;
exports.makeApi = makeApi;
exports.makeModel = makeModel;
/* ./api Not a pure module */
