// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

function getSwaggerJson(url) {
  return Axios.get(url).then(function (res) {
              if (res.status === 200) {
                return Promise.resolve(res.data);
              } else {
                return Promise.resolve(undefined);
              }
            });
}

var $$default = getSwaggerJson;

exports.getSwaggerJson = getSwaggerJson;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* axios Not a pure module */
